### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by kisyular** [kisyular/MI-449-SS17-740-html-multiple-pages-T_njfg#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://mi-449-ss17-740-html-multiple-pages-t_njfg-kisyular.surge.sh/) and meets the following criteria:

- [x] None of the routes on the website end with `.html`
- [x] A homepage exists, where the purpose of the site is explained
- [x] A "list page" exists that lists your top 3 favorite of this thing (e.g. `/pokemon`) -- each list item should link to the corresponding page for that favorite, detailed below
- [x] For each of your favorites, a page exists to display more information about it (e.g. `/pokemon/bulbasaur`)
- [x] Every page includes links to the homepage and list page (although pages do not have to link to themselves)

**Comment by stuartpearman** [comment]
Hey Rellika, your hosted link doesn't appear to be working. Did you run the surge command in your terminal?

**Comment by kisyular** [comment]
@stuartpearman I fixed the issue. It is supposed to be working now

**Comment by stuartpearman** [comment]
Hey Rellika. This is pretty awesome, you really went the extra mile here!

Your link to `/pokemon/littleduck/` doesn't appear to work, other than that, everything works fine. The only other thing I would change is this:

Check out criteria #4:

> For each of your favorites, a page exists to display more information about it (e.g. /pokemon/bulbasaur)

Right now you have /pokemon/ as your route to your list page. That works in the example because the fansite is _about_ pokemon. Try to make yours something that more closely describes the content (movies, games, music).

Let me know if you need me to clarify anything!

**Comment by kisyular** [comment]
@stuartpearman, I fixed the broken link _/pokemon/littleduck/_

I also changed the name of the route to something connected with the kinds of the content i have

**Comment by stuartpearman** [comment]
Awesome, good job Rellika! :shipit:
